keys:
  - &ArtemKhel age1u32aafyq5card7mw7wpkvp7kelfdu9pyyu26lz6v2nhn28kemytqmk0vew
  - &VPS age1epr5x6krgmt38m0g69t3t3zn400fm2hdtuvcpqw9a29y7r8wdu7s0h4c52
creation_rules:
  - path_regex: ^secrets.yaml$
    key_groups:
      - age:
          - *ArtemKhel
          - *VPS
